---
- name: Install software
  hosts: localhost
  become: true
  gather_facts: true
  vars:
   ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Get current user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

    - name: Install the rpmfusion repo packages
      dnf:
        name:
          - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version}}.noarch.rpm
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version}}.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Import teamviewer key
      ansible.builtin.rpm_key:
        key: https://linux.teamviewer.com/pubkey/currentkey.asc
        state: present

    - name: Upgrade the 'Multimedia' package group
      ansible.builtin.dnf:
        name: '@multimedia'
        state: latest
        allowerasing: true

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install rpms manually
      ansible.builtin.dnf:
        name:
          - https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
          - https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
        state: present
        disable_gpg_check: true

    - name: Install packages from rpm repos
      ansible.builtin.dnf:
        name:
          - adobe-source-sans-pro-fonts
          - age
          - ansible
          - clamav
          - dconf-editor
          - edk2-ovmf
          - fastfetch
          - flatseal
          - file-roller
          - gimp
          - gnome-epub-thumbnailer
          - gnome-tweaks
          - gnome-shell-extension-caffeine
          - gnome-shell-extension-dash-to-panel
          - gnome-shell-extension-no-overview
          - gnome-extensions-app
          - gum
          - htop
          - inkscape
          - langpacks-de
          - langpacks-fr
          - langpacks-nl
          - langpacks-pl
          - libheif-tools
          - lynis
          - mozilla-fira-sans-fonts
          - mpv
          - mupdf
          - neovim
          - pass
          - pass-otp
          - pdftk
          - swtpm
          - syncthing
          - tldr
          - thunderbird
          - totem-video-thumbnailer
          - zbar
          - zoxide
          - teamviewer
          - '@virtualization'
        state: present

    - name: Install flatpak apps
      community.general.flatpak:
        name:
          - org.nickvision.tagger
          - com.github.tchx84.Flatseal
        state: present

    - name: Install hyprland environment
      block:
      
      - name: Install bluetuith copr repo
        community.general.copr:
          name: lxdes/bluetuith
          host: copr.fedorainfracloud.org
          state: enabled

      - name: Install hyprland copr repo
        community.general.copr:
          name: acidburnmonkey/hyprland
          host: copr.fedorainfracloud.org
          state: enabled

      - name: Hyprland. Install rpms
        ansible.builtin.dnf:
          name:
            - brightnessctl
            - dunst
            - hypridle
            - hyprland
            - hyprlock
            - hyprpaper
            - kitty
            - waybar
            - hyprland-guiutils
            - wofi
            - xdg-desktop-portal-hyprland
            - blueman
            - network-manager-applet
            - pavucontrol
            - NetworkManager-tui
            - bluetuith
          state: present

