---
- name: Install software
  hosts: localhost
  become: true
  connection: local
  gather_facts: true

  tasks:
    - name: Get current user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

  - name: Uninstall unneeded packages
    ansible.builtin.dnf:
      name:
        - baobab
        - gnome-abrt
        - gnome-logs
        - gnome-maps
        - gnome-tour
        - gnome-weather
        - mediawriter
        - totem
      state: absent
      autoremove: yes

    - name: Install MS Core Fonts
      ansible.builtin.dnf:
        name: 'https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm'
        state: present

    - name: Upgrade the 'Multimedia' package group
      ansible.builtin.dnf:
      name: '@Multimedia'
      state: latest
      allowerasing: true

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install packages from rpm repos
      ansible.builtin.dnf:
        name:
          - age
          - ansible
          - celluloid
          - clamav
          - dconf-editor
          - geary
          - gimp
          - gnome-shell-extension-caffeine
          - gnome-shell-extension-no-overview
          - gnome-extensions-app
          - htop
          - inkscape
          - langpacks-de
          - langpacks-fr
          - langpacks-nl
          - langpacks-pl
          - lynis
          - neofetch
          - mpv
          - neovim
          - pass
          - pass-otp
          - syncthing
          - tldr
          - zbar
          - teamviewer
          - brave-browser
        state: present


    - name: Install flatpak apps
      community.general.flatpak:
        name:
          - com.github.tchx84.Flatseal
          - org.gnome.World.PikaBackup
          - org.nickvision.tagger
        state: present
