---
- name: Install software
  hosts: localhost
  become: true
  connection: local
  gather_facts: true

  tasks:
    - name: Get current user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

    - name: Uninstall unneeded packages
      ansible.builtin.dnf:
        name:
          - baobab
          - fedora-bookmarks
          - gnome-abrt
          - gnome-boxes
          - gnome-logs
          - gnome-maps
          - gnome-tour
          - gnome-weather
          - mediawriter
          - totem
        state: absent
        autoremove: true

    - name: Install the rpmfusion repo packages
      dnf:
        name:
          - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version}}.noarch.rpm
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version}}.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Enable Fedora Copr for LXD
        host: copr.fedorainfracloud.org
        name: jstaf/onedriver
        state: enabled

    - name: Add Brave Browser Repo
      ansible.builtin.yum_repository:
        name: brave-browser
        description: Brave Browser
        baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/
        gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
        gpgcheck: true
        enabled: true

    - name: Import brave key
      ansible.builtin.rpm_key:
        key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
        state: present

    - name: Import teamviewer key
      ansible.builtin.rpm_key:
        key: https://linux.teamviewer.com/pubkey/currentkey.asc
        state: present

    - name: Upgrade the 'Multimedia' package group
      ansible.builtin.dnf:
        name: '@Multimedia'
        state: latest
        allowerasing: true

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install rpms manually
      ansible.builtin.dnf:
        name:
          - https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
          - https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
        state: present
        disable_gpg_check: true

    - name: Install packages from rpm repos
      ansible.builtin.dnf:
        name:
          - age
          - ansible
          - celluloid
          - clamav
          - dconf-editor
          - edk2-ovmf
          - flatseal
          - geary
          - gimp
          - gnome-tweaks
          - gnome-shell-extension-caffeine
          - gnome-shell-extension-dash-to-panel
          - gnome-shell-extension-no-overview
          - gnome-extensions-app
          - htop
          - inkscape
          - langpacks-de
          - langpacks-fr
          - langpacks-nl
          - langpacks-pl
          - lynis
          - neofetch
          - mpv
          - neovim
          - onedriver
          - pass
          - pass-otp
          - swtpm
          - syncthing
          - tldr
          - zbar
          - teamviewer
          - brave-browser
          - '@Virtualization'
        state: present


    - name: Install flatpak apps
      community.general.flatpak:
        name:
          - org.gnome.World.PikaBackup
          - org.nickvision.tagger
        state: present
