---
- name: Install software
  hosts: localhost
  become: true
  connection: local
  gather_facts: true

  tasks:
    - name: Get current user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

    - name: Uninstall unneeded packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
        autoremove: true
      with_items:
        - baobab
        - gnome-abrt
        - gnome-logs
        - gnome-maps
        - gnome-tour
        - gnome-weather
        - mediawriter
        - totem

    - name: install the rpmfusion repo packages
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version}}.noarch.rpm
        - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version}}.noarch.rpm


    - name: Import GPG Keys
      ansible.builtin.rpm_key:
        key: "{{ item }}"
        state: present
      with_items:
        - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
        - https://linux.teamviewer.com/pubkey/currentkey.asc

    - name: Add Brave Browser Repo
      ansible.builtin.yum_repository:
        name: brave-browser
        description: Brave Browser
        baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/
        gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
        gpgcheck: true
        enabled: true

    - name: Add TeamViewer Repo
      ansible.builtin.yum_repository:
        name: teamviewer
        description: TeamViewer - $basearch
        baseurl: https://linux.teamviewer.com/yum/stable/main/binary-$basearch/
        gpgkey: https://linux.teamviewer.com/pubkey/currentkey.asc
        gpgcheck: true
        repo_gpgcheck: true
        enabled: true

    - name: Install MS Core Fonts
      ansible.builtin.dnf:
        name: 'https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm'
        state: present
        disable_gpg_check: true

    - name: Upgrade the 'Multimedia' package group
      ansible.builtin.dnf:
        name: '@Multimedia'
        state: latest
        allowerasing: true

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install packages from rpm repos
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - age
        - ansible
        - celluloid
        - clamav
        - dconf-editor
        - geary
        - gimp
        - gnome-shell-extension-caffeine
        - gnome-shell-extension-no-overview
        - gnome-extensions-app
        - htop
        - inkscape
        - langpacks-de
        - langpacks-fr
        - langpacks-nl
        - langpacks-pl
        - lynis
        - neofetch
        - mpv
        - neovim
        - pass
        - pass-otp
        - syncthing
        - tldr
        - zbar
        - teamviewer
        - brave-browser

    - name: Install flatpak apps
      community.general.flatpak:
        name:  "{{ item }}"
        state: present
      with_items:
        - com.github.tchx84.Flatseal
        - org.gnome.World.PikaBackup
        - org.nickvision.tagger
