---
- name: Install software
  hosts: localhost
  become: true
  connection: local
  gather_facts: true

  tasks:
    - name: Get current user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

    - name: Uninstall unneeded packages
      ansible.builtin.dnf:
        name:
          - abrt-desktop
          - baobab
          - fedora-bookmarks
          - geary
          - gnome-boxes
          - gnome-calendar
          - gnome-contacts
          - gnome-logs
          - gnome-maps
          - gnome-tour
          - gnome-weather
          - mediawriter
          - ibus-hangul
          - ibus-libpinyin
          - ibus-libzhuyin
          - totem
        state: absent
        autoremove: yes

    - name: Install the rpmfusion repo packages
      dnf:
        name:
          - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version}}.noarch.rpm
          - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version}}.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Import teamviewer key
      ansible.builtin.rpm_key:
        key: https://linux.teamviewer.com/pubkey/currentkey.asc
        state: present

    - name: Upgrade the 'Multimedia' package group
      ansible.builtin.dnf:
        name: '@Multimedia'
        state: latest
        allowerasing: true

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install rpms manually
      ansible.builtin.dnf:
        name:
          - https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
          - https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
        state: present
        disable_gpg_check: true

    - name: Install packages from rpm repos
      ansible.builtin.dnf:
        name:
          - age
          - ansible
          - celluloid
          - clamav
          - dconf-editor
          - edk2-ovmf
          - fastfetch
          - flatseal
          - file-roller
          - foliate
          - geary
          - gimp
          - gnome-epub-thumbnailer
          - gnome-tweaks
          - gnome-shell-extension-caffeine
          - gnome-shell-extension-dash-to-panel
          - gnome-shell-extension-no-overview
          - gnome-extensions-app
          - htop
          - inkscape
          - langpacks-de
          - langpacks-fr
          - langpacks-nl
          - langpacks-pl
          - libheif-tools
          - lynis
          - mpv
          - neovim
          - pass
          - pass-otp
          - pdftk
          - swtpm
          - syncthing
          - tldr
          - thunderbird
          - totem-video-thumbnailer
          - zbar
          - teamviewer
          - '@Virtualization'
        state: present

    - name: Install flatpak apps
      community.general.flatpak:
        name:
          - org.gnome.World.PikaBackup
          - org.nickvision.tagger
          - org.gnome.Totem
        state: present

    - name: Alienfx-gtk. Install dependencies, pull project from github, install binaries
      when: ansible_facts['bios_vendor'] == "Alienware"
      block:

      - name: Alienfx. Install rpms
        ansible.builtin.dnf:
          name:
            - cairo-devel
            - pipx
            - python3-pyusb
            - gobject-introspection
            - gtk3-devel
          state: present

      - name: Alienfx. Ensure path for python modules
        ansible.builtin.shell: pipx ensurepath --global

      - name: Alienfx. Install python modules
        community.general.pipx:
          name: future
          state: present
          global: true

      - name: Alienfx. Clone git repo
        ansible.builtin.git:
          repo: https://github.com/trackmastersteve/alienfx.git
          dest: /src/alienfx

      - name: Alienfx. Install binaries
        ansible.builtin.shell:
          cmd: sudo python3 setup.py install && sudo python3 setup.py install_data
          chdir: /src/alienfx

    - name: Install hyprland
      block:

      - name: Install copr repo
        community.general.copr:
          name: solopasha/hyprland
          host: copr.fedorainfracloud.org
          state: enabled

      - name: Hyprland. Install rpms
        ansible.builtin.dnf:
          name:
            - hypridle
            - hyprland
            - hyprlock
            - hyprshot
            - kitty
            - waybar
            - xdg-desktop-portal-hyprland
          state: present

